@startuml
title Twitter

class User {
	+ id : Number
	+ username : string
	+ password : string
	+ profile : Profile
	+ tweets : Tweet[]
}

class Tweet {
	+ id : Number
	+ user : string
	+ body : string
	+ time : Number
}

class UserModel {
	+ createUser(username : string, password: string, email : string) : User
	+ removeUser(userId : Number)
	+ login(username : string, password : string)
	+ logout()
	+ getUserById(userId : Number)
	+ getUserByUsername(username : string)
}

class Session {
	+ userId : Number
}

class FollowManager {
	+ follow(follower : User, following : User)
	+ getFollowingByUserId(userId : Number) : User[]
	+ getFollowersByUserId(userId : Number) : User[]
}

class Profile {
	+ id : Number
	+ user : User
	+ bio : string
	+ photoUrl : string
	+ location : string
}

class ProfileModel {
	+ createProfile(user: User, bio : string, photoUrl : string, location : string)
	+ getProfileByUserId(userId : Number) : Profile
	+ editProfileByUserId(userId : Number, newProfile : Profile)
}

class TweetModel {
	+ postTweet(user : User, body : Body)
	+ removeTweet(tweetId : Number)
	+ getTweetsByUserId(userId : Number) : Tweet[]
}

class DirectMessage {
	+ from : User
	+ to : User
	+ body : string
}

class DirectMessageModel {
	+ sendDirectMessage(from : User, to : User, body : string)
	+ getInboxByUserId(userId : Number) : DirectMessage[]
	+ getSentByUserId(userId : Number) : DirectMessage[]
}

@enduml