@startuml
title Twitter

class User {
	+ id : Number
	+ username : string
	+ password : string
}

class Tweet {
	+ id : Number
	+ userId : Number
	+ body : string
	+ time : Number
}

class UserModel {
	+ createUser(username : string, password: string, email : string) : User
	+ removeUser(userId : Number)
	+ login(username : string, password : string)
	+ logout()
	+ getUserById(userId : Number)
	+ getUserByUsername(username : string)
}

class Session {
	+ userId : Number
}

class FollowManager {
	+ createFollow(follower : User, following : User)
	+ getFollowingByUserId(userId : Number) : User[]
	+ getFollowersByUserId(userId : Number) : User[]
}

class Profile {
	+ id : Number
	+ userId : Number
	+ bio : string
	+ photoUrl : string
	+ location : string
}

class ProfileModel {
	+ createProfile(bio : string, photoUrl : string, location : string)
	+ getProfileByUserId(userId : Number) : Profile
	+ editProfileByUserId(userId : Number, newProfile : Profile)
}

class TweetModel {
	+ postTweet(user : User, body : string)
	+ removeTweet(tweetId : Number)
	+ getTweetsByUserId(userId : Number) : Tweet[]
}

class DirectMessage {
	+ id : Number
	+ fromId : Number
	+ toId : Number
	+ body : string
}

class DirectMessageModel {
	+ sendDirectMessage(from : User, to : User, body : string)
	+ getInboxByUserId(userId : Number) : DirectMessage[]
	+ getSentByUserId(userId : Number) : DirectMessage[]
}

class Follow {
	+ id : Number
	+ followerId : Number
	+ followingId : Number
}

UserModel o-- User
UserModel o-- Session
DirectMessageModel o-- DirectMessage
ProfileModel o-- Profile
TweetModel o-- Tweet
FollowManager o-- Follow
User .. Session
User .. Tweet
User .. Profile
User .. DirectMessage
Follow .. User
FollowManager .. User
@enduml